# permissions to do viewer harbors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: harbor-viewer-role
rules:
- apiGroups:
  - goharbor.io
  resources:
  - harbors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - goharbor.io
  resources:
  - harbors/status
  verbs:
  - get
