# permissions for end users to edit harborclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: harborcluster-editor-role
rules:
- apiGroups:
  - goharbor.io
  resources:
  - harborclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - goharbor.io
  resources:
  - harborclusters/status
  verbs:
  - get
  - patch
  - update