{{- if or (eq .Values.postgres_operator.backup.enabled true) (eq.Values.postgres_operator.restore.enabled true) -}}
apiVersion: v1
kind: Secret
metadata:
  labels: {{- include "chart.labels" . | nindent 4 }}
  name: 'pod-secret'
  namespace: {{ .Release.Namespace | quote }}
data:
  {{- if eq .Values.postgres_operator.backup.enabled true }}
    AWS_ACCESS_KEY_ID: {{ .Values.postgres_operator.backup.aws.accessKeyID | b64enc | quote }}
    AWS_SECRET_ACCESS_KEY: {{ .Values.postgres_operator.backup.aws.secretKey | b64enc | quote }}
  {{- end }}

  {{- if eq .Values.postgres_operator.restore.enabled true }}

  {{- if .Values.postgres_operator.restore.aws.accessKeyID }}
    CLONE_AWS_ACCESS_KEY_ID: {{ .Values.postgres_operator.restore.aws.accessKeyID | b64enc | quote }}
  {{- else}}
    CLONE_AWS_ACCESS_KEY_ID: {{ .Values.postgres_operator.backup.aws.accessKeyID | b64enc | quote }}
  {{- end }}

  {{- if .Values.postgres_operator.restore.aws.secretKey }}
    CLONE_AWS_SECRET_ACCESS_KEY: {{ .Values.postgres_operator.restore.aws.secretKey | b64enc | quote }}
  {{- else}}
    CLONE_AWS_SECRET_ACCESS_KEY: {{ .Values.postgres_operator.backup.aws.secretKey | b64enc | quote }}
  {{- end }}

  {{- end }}
{{- end }}

