{{- if or (eq (index .Values "postgres-operator" "backup" "enabled") true) (eq (index .Values "postgres-operator" "restore" "enabled") true) }}
apiVersion: v1
kind: Secret
metadata:
  labels: {{- include "chart.labels" . | nindent 4 }}
  name: 'pod-secret'
  namespace: {{ .Release.Namespace | quote }}
data:
  {{- if (eq (index .Values "postgres-operator" "backup" "enabled") true) }}
    AWS_ACCESS_KEY_ID: {{ index .Values "postgres-operator" "backup" "aws" "accessKeyID" | b64enc | quote }}
    AWS_SECRET_ACCESS_KEY: {{ index .Values "postgres-operator" "backup" "aws" "secretKey" | b64enc | quote }}
  {{- end }}

  {{- if index .Values "postgres-operator" "restore" "enabled" }}

  {{- if index .Values "postgres-operator" "restore" "aws" "accessKeyID" }}
    CLONE_AWS_ACCESS_KEY_ID: {{ index .Values "postgres-operator" "restore" "aws" "accessKeyID" | b64enc | quote }}
  {{- else}}
    CLONE_AWS_ACCESS_KEY_ID: {{ index .Values "postgres-operator" "backup" "aws" "accessKeyID" | b64enc | quote }}
  {{- end }}

  {{- if  index .Values "postgres-operator" "restore" "aws" "secretKey" }}
    CLONE_AWS_SECRET_ACCESS_KEY: {{ index .Values "postgres-operator" "restore" "aws" "secretKey" | b64enc | quote }}
  {{- else}}
    CLONE_AWS_SECRET_ACCESS_KEY: {{ index .Values "postgres-operator" "backup" "aws" "secretKey" | b64enc | quote }}
  {{- end }}

  {{- end }}
{{- end }}

