{{- if or (eq (index .Values "postgres-operator" "backup" "enabled") true) (eq (index .Values "postgres-operator" "restore" "enabled") true) }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels: {{- include "chart.labels" . | nindent 4 }}
  name: 'pod-config'
  namespace: {{ .Release.Namespace | quote }}
data:
  {{- if (eq (index .Values "postgres-operator" "backup" "enabled") true) }}
    USE_WALG_BACKUP: "true"
    WALG_DISABLE_S3_SSE: "true"
    WALE_DISABLE_S3_SSE: "true"
    NUMBER_OF_BACKUPS_TO_RETAIN: {{ index .Values "postgres-operator" "backup" "number_of_backups_to_retain" | quote }}
    BACKUP_SCHEDULE: {{ index .Values "postgres-operator" "backup" "backup_schedule" | quote }}
    AWS_REGION: {{ index .Values "postgres-operator" "backup" "aws" "region" | quote }}
    AWS_ACCESS_KEY_ID: {{ index .Values "postgres-operator" "backup" "aws" "accessKeyID" | quote }}
    AWS_SECRET_ACCESS_KEY: {{ index .Values "postgres-operator" "backup" "aws" "secretKey" | quote }}
  {{- end }}

  {{- if index .Values "postgres-operator" "restore" "enabled" }}
    USE_WALG_RESTORE: "true"
    CLONE_USE_WALG_RESTORE: "true"
    CLONE_METHOD: "CLONE_WITH_WALE"

    CLONE_HOST: {{ index .Values "postgres-operator" "restore" "host" | quote }}
    CLONE_PORT: "5432"
    CLONE_USER: "postgres"

    CLONE_SCOPE: {{ index .Values "postgres-operator" "restore" "scope" | quote }}
    CLONE_WAL_BUCKET_SCOPE_SUFFIX: {{ index .Values "postgres-operator" "restore" "scope_suffix" | quote }}

  {{- if index .Values "postgres-operator" "restore" "aws" "region" }}
    CLONE_AWS_REGION: {{ index .Values "postgres-operator" "restore" "aws" "region" | quote }}
  {{- else }}
    CLONE_AWS_REGION: {{ index .Values "postgres-operator" "restore" "aws" "region" | quote }}
  {{- end }}

  {{- if index .Values "postgres-operator" "restore" "bucket" }}
    CLONE_WAL_S3_BUCKET: {{ index .Values "postgres-operator" "restore" "bucket" | quote }}
  {{- else }}
    CLONE_WAL_S3_BUCKET: {{ index .Values "postgres-operator" "configAwsOrGcp" "wal_s3_bucket" | quote }}
  {{- end }}
  {{- if index .Values "postgres-operator" "restore" "aws" "accessKeyID" }}
    CLONE_AWS_ACCESS_KEY_ID: {{ index .Values "postgres-operator" "restore" "aws" "accessKeyID" | b64enc | quote }}
  {{- else}}
    CLONE_AWS_ACCESS_KEY_ID: {{ index .Values "postgres-operator" "backup" "aws" "accessKeyID" | b64enc | quote }}
  {{- end }}

  {{- if  index .Values "postgres-operator" "restore" "aws" "secretKey" }}
    CLONE_AWS_SECRET_ACCESS_KEY: {{ index .Values "postgres-operator" "restore" "aws" "secretKey" | b64enc | quote }}
  {{- else}}
    CLONE_AWS_SECRET_ACCESS_KEY: {{ index .Values "postgres-operator" "backup" "aws" "secretKey" | b64enc | quote }}
  {{- end }}


  {{- end }}
{{- end }}

