apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: test
  labels:
    app.kubernetes.io/name: {{ template "postgres-operator.name" . }}
    helm.sh/chart: {{ template "postgres-operator.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
rules:
# to let postgres pod create emptyDir and configMap volume
- apiGroups:
    - policy
  resources:
    - podsecuritypolicies
  verbs:
    - use
  resourceNames:
    - '{{ include "postgres-pod.serviceAccountName" . }}-psp'
