apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: '{{ include "postgres-pod.serviceAccountName" . }}-psp'
  labels: {{- include "chart.labels" . | nindent 4 }}
spec:
  privileged: false
  allowPrivilegeEscalation: true
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
    - configMap
    - emptyDir
    - persistentVolumeClaim
    - projected
    - secret
    - downwardAPI
  
