version: "3.7"
services:
  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    networks:
      - frontend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  frontend:
